# Generated by Django 5.1.2 on 2024-10-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chineseDishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('capital', models.TextField(verbose_name='Столица')),
                ('population', models.TextField(verbose_name='Население')),
                ('area', models.TextField(verbose_name='Площадь')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
    ]
