# Generated by Django 5.1.2 on 2024-10-13 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chineseDishes', '0002_province_delete_dish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'Провинция', 'verbose_name_plural': 'Провинции'},
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.TextField(verbose_name='Категория')),
                ('spice_level', models.TextField(verbose_name='Уровень остроты')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chineseDishes.province')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
    ]
