# Generated by Django 5.1.2 on 2024-10-14 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chineseDishes', '0003_alter_province_options_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingridient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('category', models.TextField(verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Ингридиент',
                'verbose_name_plural': 'Ингридиенты',
            },
        ),
        migrations.AlterField(
            model_name='dish',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chineseDishes.province', verbose_name='Провинция'),
        ),
        migrations.CreateModel(
            name='Dish_Ingridient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.TextField(verbose_name='Количество')),
                ('dish_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chineseDishes.dish', verbose_name='Блюдо')),
                ('ingridient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chineseDishes.ingridient', verbose_name='Ингридиент')),
            ],
            options={
                'verbose_name': 'Блюдо_Ингридент',
                'verbose_name_plural': 'Блюда_Ингриденты',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='ingridients',
            field=models.ManyToManyField(through='chineseDishes.Dish_Ingridient', to='chineseDishes.ingridient'),
        ),
    ]
