# Generated by Django 5.1.2 on 2024-10-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chineseDishes', '0004_ingridient_alter_dish_province_dish_ingridient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish_ingridient',
            old_name='dish_id',
            new_name='dish',
        ),
        migrations.RenameField(
            model_name='dish_ingridient',
            old_name='ingridient_id',
            new_name='ingridient',
        ),
    ]
