# Generated by Django 5.1.2 on 2024-10-14 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chineseDishes', '0005_rename_dish_id_dish_ingridient_dish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingridients',
        ),
    ]
