# Generated by Django 5.1.2 on 2024-10-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chineseDishes', '0006_remove_dish_ingridients'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='ingridients',
            field=models.ManyToManyField(through='chineseDishes.Dish_Ingridient', to='chineseDishes.ingridient'),
        ),
    ]
