# Generated by Django 5.1.2 on 2024-10-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chineseDishes', '0007_dish_ingridients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridient',
            name='category',
            field=models.CharField(choices=[('Мясо', 'Meat'), ('Молочные продукты', 'Milk'), ('Крупы', 'Sereals')], max_length=30),
        ),
    ]
