# Generated by Django 5.1.2 on 2024-10-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chineseDishes', '0008_alter_ingridient_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridient',
            name='category',
            field=models.CharField(choices=[('MT', 'Мясо'), ('MK', 'Молочные продукты'), ('SRL', 'Крупы')], max_length=30),
        ),
    ]
