# Generated by Django 5.1.2 on 2024-10-15 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chineseDishes', '0011_alter_ingridient_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='spice_level',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Уровень остроты'),
        ),
    ]
