# Generated by Django 5.1.2 on 2024-10-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chineseDishes', '0012_alter_dish_spice_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish_ingridient',
            name='typeQuantity',
            field=models.CharField(choices=[('гр', 'гр'), ('мл', 'мл'), (' ст.', 'ст.'), ('ч.л.', 'Smlspoon'), ('ст.л.', 'Bgspoon')], default='GR', max_length=10, verbose_name='Измерение'),
        ),
        migrations.AlterField(
            model_name='dish_ingridient',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
    ]
