# Generated by Django 5.1.2 on 2024-10-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chineseDishes', '0013_dish_ingridient_typequantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish_ingridient',
            name='typeQuantity',
            field=models.CharField(choices=[('гр', 'гр'), ('мл', 'мл'), (' ст.', 'Glass'), ('ч.л.', 'Smlspoon'), ('ст.л.', 'Bgspoon')], default='GR', max_length=10, verbose_name='Измерение'),
        ),
    ]
