# Generated by Django 5.1.2 on 2024-10-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chineseDishes', '0014_alter_dish_ingridient_typequantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish_ingridient',
            name='typeQuantity',
            field=models.CharField(choices=[('гр', 'гр'), ('мл', 'мл'), (' ст.', 'ст.'), ('ч.л.', 'ч.л.'), ('ст.л.', 'ст.л.')], default='GR', max_length=10, verbose_name='Измерение'),
        ),
    ]
