# Generated by Django 5.1.2 on 2024-10-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chineseDishes', '0016_alter_dish_ingridient_typequantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('Десерт', 'Десерт'), ('Горячее', 'Горячее'), ('Напиток', 'Напиток')], default='HOT', max_length=30, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='province',
            name='area',
            field=models.PositiveIntegerField(verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='province',
            name='population',
            field=models.PositiveIntegerField(verbose_name='Население'),
        ),
    ]
