# Generated by Django 5.1.2 on 2024-10-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chineseDishes', '0017_alter_dish_category_alter_province_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('Десерт', 'Десерт'), ('Горячее', 'Горячее'), ('Напиток', 'Напиток')], max_length=30, verbose_name='Категория'),
        ),
    ]
