# Generated by Django 5.1.2 on 2024-10-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chineseDishes', '0019_alter_province_area_alter_province_population'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingridients',
        ),
    ]
