# Generated by Django 5.1 on 2024-12-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chineseDishes', '0021_dish_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='picture',
            field=models.ImageField(null=True, upload_to='chineseDishes', verbose_name='Изображение'),
        ),
    ]
